# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
=begin
Hphrase.create(title:'H200', description: 'Instabil, explosiv')
Hphrase.create(title:'H201', description: 'Explosiv, Gefahr der Massenexplosion')
Hphrase.create(title:'H202', description: 'Explosiv; große Gefahr durch Splitter, Spreng- und Wurfstücke')
Hphrase.create(title:'H203', description: 'Explosiv; Gefahr durch Feuer, Luftdruck oder Splitter, Spreng- und Wurfstücke')
Hphrase.create(title:'H204', description: 'Gefahr durch Feuer oder Splitter, Spreng- und Wurfstücke')
Hphrase.create(title:'H205', description: 'Gefahr der Massenexplosion bei Feuer')
Hphrase.create(title:'H220', description: 'Extrem entzündbares Gas')
Hphrase.create(title:'H221', description: 'Entzündbares Gas')
Hphrase.create(title:'H222', description: 'Extrem entzündbares Aerosol')
Hphrase.create(title:'H223', description: 'Entzündbares Aerosol')
Hphrase.create(title:'H224', description: 'Flüssigkeit und Dampf extrem entzündbar')
Hphrase.create(title:'H225', description: 'Flüssigkeit und Dampf leicht entzündbar')
Hphrase.create(title:'H226', description: 'Flüssigkeit und Dampf entzündbar')
Hphrase.create(title:'H228', description: 'Entzündbarer Feststoff')
Hphrase.create(title:'H229', description: 'Behälter steht unter Druck: kann bei Erwärmung bersten')
Hphrase.create(title:'H230', description: 'Kann auch in Abwesenheit von Luft explosionsartig reagieren')
Hphrase.create(title:'H231', description: 'Kann auch in Abwesenheit von Luft bei erhöhtem Druck und/oder erhöhter Temperatur explosionsartig reagieren')
Hphrase.create(title:'H240', description: 'Erwärmung kann Explosion verursachen')
Hphrase.create(title:'H241', description: 'Erwärmung kann Brand oder Explosion verursachen')
Hphrase.create(title:'H242', description: 'Erwärmung kann Brand verursachen')
Hphrase.create(title:'H250', description: 'Entzündet sich in Berührung mit Luft von selbst')
Hphrase.create(title:'H251', description: 'Selbsterhitzungsfähig; kann in Brand geraten')
Hphrase.create(title:'H252', description: 'In großen Mengen selbsterhitzungsfähig; kann in Brand geraten')
Hphrase.create(title:'H260', description: 'In Berührung mit Wasser entstehen entzündbare Gase, die sich spontan entzünden können')
Hphrase.create(title:'H261', description: 'In Berührung mit Wasser entstehen entzündbare Gase')
Hphrase.create(title:'H270', description: 'Kann Brand verursachen oder verstärken; Oxidationsmittel')
Hphrase.create(title:'H271', description: 'Kann Brand oder Explosion verursachen; starkes Oxidationsmittel')
Hphrase.create(title:'H272', description: 'Kann Brand verstärken; Oxidationsmittel')
Hphrase.create(title:'H280', description: 'Enthält Gas unter Druck; kann bei Erwärmung explodieren')
Hphrase.create(title:'H281', description: 'Enthält tiefgekühltes Gas; kann Kälteverbrennungen oder -verletzungen verursachen')
Hphrase.create(title:'H290', description: 'Kann gegenüber Metallen korrosiv sein')
Hphrase.create(title:'H300', description: 'Lebensgefahr bei Verschlucken')
Hphrase.create(title:'H301', description: 'Giftig bei Verschlucken')
Hphrase.create(title:'H302', description: 'Gesundheitsschädlich bei Verschlucken')
Hphrase.create(title:'H304', description: 'Kann bei Verschlucken und Eindringen in die Atemwege tödlich sein')
Hphrase.create(title:'H310', description: 'Lebensgefahr bei Hautkontakt')
Hphrase.create(title:'H311', description: 'Giftig bei Hautkontakt')
Hphrase.create(title:'H312', description: 'Gesundheitsschädlich bei Hautkontakt')
Hphrase.create(title:'H314', description: 'Verursacht schwere Verätzungen der Haut und schwere Augenschäden')
Hphrase.create(title:'H315', description: 'Verursacht Hautreizungen')
Hphrase.create(title:'H317', description: 'Kann allergische Hautreaktionen verursachen')
Hphrase.create(title:'H318', description: 'Verursacht schwere Augenschäden')
Hphrase.create(title:'H319', description: 'Verursacht schwere Augenreizung')
Hphrase.create(title:'H330', description: 'Lebensgefahr bei Einatmen')
Hphrase.create(title:'H331', description: 'Giftig bei Einatmen')
Hphrase.create(title:'H332', description: 'Gesundheitsschädlich bei Einatmen')
Hphrase.create(title:'H334', description: 'Kann bei Einatmen Allergie, asthmaartige Symptome oder Atembeschwerden verursachen')
Hphrase.create(title:'H335', description: 'Kann die Atemwege reizen')
Hphrase.create(title:'H336', description: 'Kann Schläfrigkeit und Benommenheit verursachen')
Hphrase.create(title:'H340', description: 'Kann genetische Defekte verursachen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H341', description: 'Kann vermutlich genetische Defekte verursachen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H350', description: 'Kann Krebs erzeugen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H350i', description: 'Kann bei Einatmen Krebs erzeugen')
Hphrase.create(title:'H351', description: 'Kann vermutlich Krebs erzeugen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H360', description: 'Kann die Fruchtbarkeit beeinträchtigen oder das Kind im Mutterleib schädigen (konkrete Wirkung angeben, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass die Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H360F', description: 'Kann die Fruchtbarkeit beeinträchtigen')
Hphrase.create(title:'H360D', description: 'Kann das Kind im Mutterleib schädigen')
Hphrase.create(title:'H360FD', description: 'Kann die Fruchtbarkeit beeinträchtigen Kann das Kind im Mutterleib schädigen')
Hphrase.create(title:'H360Fd', description: 'Kann die Fruchtbarkeit beeinträchtigen Kann vermutlich das Kind im Mutterleib schädigen')
Hphrase.create(title:'H360Df', description: 'Kann das Kind im Mutterleib schädigen Kann vermutlich die Fruchtbarkeit beeinträchtigen')
Hphrase.create(title:'H361', description: 'Kann vermutlich die Fruchtbarkeit beeinträchtigen oder das Kind im Mutterleib schädigen (konkrete Wirkung angeben, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass die Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H361f', description: 'Kann vermutlich die Fruchtbarkeit beeinträchtigen')
Hphrase.create(title:'H361d', description: 'Kann vermutlich das Kind im Mutterleib schädigen')
Hphrase.create(title:'H361fd', description: 'Kann vermutlich die Fruchtbarkeit beeinträchtigen Kann vermutlich das Kind im Mutterleib schädigen')
Hphrase.create(title:'H362', description: 'Kann Säuglinge über die Muttermilch schädigen')
Hphrase.create(title:'H370', description: 'Schädigt die Organe (oder alle betroffenen Organe nennen, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H371', description: 'Kann die Organe schädigen (oder alle betroffenen Organe nennen, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H372', description: 'Schädigt die Organe (alle betroffenen Organe nennen) bei längerer oder wiederholter Exposition (Expositionsweg angeben, wenn schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H373', description: 'Kann die Organe schädigen (alle betroffenen Organe nennen, sofern bekannt) bei längerer oder wiederholter Exposition (Expositionsweg angeben, wenn schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H300+H310', description: 'Lebensgefahr bei Verschlucken oder Hautkontakt')
Hphrase.create(title:'H300+H310+H330', description: 'Lebensgefahr bei Verschlucken, Hautkontakt oder Einatmen')
Hphrase.create(title:'H300+H330', description: 'Lebensgefahr bei Verschlucken oder Einatmen')
Hphrase.create(title:'H301+H311', description: 'Giftig bei Verschlucken oder Hautkontakt')
Hphrase.create(title:'H301+H311+H331', description: 'Giftig bei Verschlucken, Hautkontakt oder Einatmen')
Hphrase.create(title:'H301+H331', description: 'Giftig bei Verschlucken oder Einatmen')
Hphrase.create(title:'H302+H312', description: 'Gesundheitsschädlich bei Verschlucken oder Hautkontakt')
Hphrase.create(title:'H302+H312+H332', description: 'Gesundheitsschädlich bei Verschlucken, Hautkontakt oder Einatmen')
Hphrase.create(title:'H302+H332', description: 'Gesundheitsschädlich bei Verschlucken oder Einatmen')
Hphrase.create(title:'H310+H330', description: 'Lebensgefahr bei Hautkontakt oder Einatmen')
Hphrase.create(title:'H311+H331', description: 'Giftig bei Hautkontakt oder Einatmen')
Hphrase.create(title:'H312+H332', description: 'Gesundheitsschädlich bei Hautkontakt oder Einatmen')
Hphrase.create(title:'H400', description: 'Sehr giftig für Wasserorganismen')
Hphrase.create(title:'H410', description: 'Sehr giftig für Wasserorganismen mit langfristiger Wirkung')
Hphrase.create(title:'H411', description: 'Giftig für Wasserorganismen, mit langfristiger Wirkung')
Hphrase.create(title:'H412', description: 'Schädlich für Wasserorganismen, mit langfristiger Wirkung')
Hphrase.create(title:'H413', description: 'Kann für Wasserorganismen schädlich sein, mit langfristiger Wirkung')
Hphrase.create(title:'H420', description: 'Schädigt die öffentliche Gesundheit und die Umwelt durch Ozonabbau in der äußeren Atmosphäre')

Pphrase.create(title:'P101', description: 'Ist ärztlicher Rat erforderlich, Verpackung oder Kennzeichnungsetikett bereithalten')
Pphrase.create(title:'P102', description: 'Darf nicht in die Hände von Kindern gelangen')
Pphrase.create(title:'P103', description: 'Vor Gebrauch Kennzeichnungsetikett lesen')

Rphrase.create(title:'R1', description: 'In trockenem Zustand explosionsgefährlich')
Rphrase.create(title:'R2', description: 'Durch Schlag, Reibung, Feuer und andere Zündquellen explosionsgefährlich')
Rphrase.create(title:'R3', description: 'Durch Schlag, Reibung, Feuer und andere Zündquellen besonders explosionsgefährlich')
=end
