# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
=begin
Hphrase.create(title:'H200', description: 'Instabil, explosiv')
Hphrase.create(title:'H201', description: 'Explosiv, Gefahr der Massenexplosion')
Hphrase.create(title:'H202', description: 'Explosiv; große Gefahr durch Splitter, Spreng- und Wurfstücke')
Hphrase.create(title:'H203', description: 'Explosiv; Gefahr durch Feuer, Luftdruck oder Splitter, Spreng- und Wurfstücke')
Hphrase.create(title:'H204', description: 'Gefahr durch Feuer oder Splitter, Spreng- und Wurfstücke')
Hphrase.create(title:'H205', description: 'Gefahr der Massenexplosion bei Feuer')
Hphrase.create(title:'H220', description: 'Extrem entzündbares Gas')
Hphrase.create(title:'H221', description: 'Entzündbares Gas')
Hphrase.create(title:'H222', description: 'Extrem entzündbares Aerosol')
Hphrase.create(title:'H223', description: 'Entzündbares Aerosol')
Hphrase.create(title:'H224', description: 'Flüssigkeit und Dampf extrem entzündbar')
Hphrase.create(title:'H225', description: 'Flüssigkeit und Dampf leicht entzündbar')
Hphrase.create(title:'H226', description: 'Flüssigkeit und Dampf entzündbar')
Hphrase.create(title:'H228', description: 'Entzündbarer Feststoff')
Hphrase.create(title:'H229', description: 'Behälter steht unter Druck: kann bei Erwärmung bersten')
Hphrase.create(title:'H230', description: 'Kann auch in Abwesenheit von Luft explosionsartig reagieren')
Hphrase.create(title:'H231', description: 'Kann auch in Abwesenheit von Luft bei erhöhtem Druck und/oder erhöhter Temperatur explosionsartig reagieren')
Hphrase.create(title:'H240', description: 'Erwärmung kann Explosion verursachen')
Hphrase.create(title:'H241', description: 'Erwärmung kann Brand oder Explosion verursachen')
Hphrase.create(title:'H242', description: 'Erwärmung kann Brand verursachen')
Hphrase.create(title:'H250', description: 'Entzündet sich in Berührung mit Luft von selbst')
Hphrase.create(title:'H251', description: 'Selbsterhitzungsfähig; kann in Brand geraten')
Hphrase.create(title:'H252', description: 'In großen Mengen selbsterhitzungsfähig; kann in Brand geraten')
Hphrase.create(title:'H260', description: 'In Berührung mit Wasser entstehen entzündbare Gase, die sich spontan entzünden können')
Hphrase.create(title:'H261', description: 'In Berührung mit Wasser entstehen entzündbare Gase')
Hphrase.create(title:'H270', description: 'Kann Brand verursachen oder verstärken; Oxidationsmittel')
Hphrase.create(title:'H271', description: 'Kann Brand oder Explosion verursachen; starkes Oxidationsmittel')
Hphrase.create(title:'H272', description: 'Kann Brand verstärken; Oxidationsmittel')
Hphrase.create(title:'H280', description: 'Enthält Gas unter Druck; kann bei Erwärmung explodieren')
Hphrase.create(title:'H281', description: 'Enthält tiefgekühltes Gas; kann Kälteverbrennungen oder -verletzungen verursachen')
Hphrase.create(title:'H290', description: 'Kann gegenüber Metallen korrosiv sein')
Hphrase.create(title:'H300', description: 'Lebensgefahr bei Verschlucken')
Hphrase.create(title:'H301', description: 'Giftig bei Verschlucken')
Hphrase.create(title:'H302', description: 'Gesundheitsschädlich bei Verschlucken')
Hphrase.create(title:'H304', description: 'Kann bei Verschlucken und Eindringen in die Atemwege tödlich sein')
Hphrase.create(title:'H310', description: 'Lebensgefahr bei Hautkontakt')
Hphrase.create(title:'H311', description: 'Giftig bei Hautkontakt')
Hphrase.create(title:'H312', description: 'Gesundheitsschädlich bei Hautkontakt')
Hphrase.create(title:'H314', description: 'Verursacht schwere Verätzungen der Haut und schwere Augenschäden')
Hphrase.create(title:'H315', description: 'Verursacht Hautreizungen')
Hphrase.create(title:'H317', description: 'Kann allergische Hautreaktionen verursachen')
Hphrase.create(title:'H318', description: 'Verursacht schwere Augenschäden')
Hphrase.create(title:'H319', description: 'Verursacht schwere Augenreizung')
Hphrase.create(title:'H330', description: 'Lebensgefahr bei Einatmen')
Hphrase.create(title:'H331', description: 'Giftig bei Einatmen')
Hphrase.create(title:'H332', description: 'Gesundheitsschädlich bei Einatmen')
Hphrase.create(title:'H334', description: 'Kann bei Einatmen Allergie, asthmaartige Symptome oder Atembeschwerden verursachen')
Hphrase.create(title:'H335', description: 'Kann die Atemwege reizen')
Hphrase.create(title:'H336', description: 'Kann Schläfrigkeit und Benommenheit verursachen')
Hphrase.create(title:'H340', description: 'Kann genetische Defekte verursachen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H341', description: 'Kann vermutlich genetische Defekte verursachen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H350', description: 'Kann Krebs erzeugen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H350i', description: 'Kann bei Einatmen Krebs erzeugen')
Hphrase.create(title:'H351', description: 'Kann vermutlich Krebs erzeugen (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H360', description: 'Kann die Fruchtbarkeit beeinträchtigen oder das Kind im Mutterleib schädigen (konkrete Wirkung angeben, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass die Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H360F', description: 'Kann die Fruchtbarkeit beeinträchtigen')
Hphrase.create(title:'H360D', description: 'Kann das Kind im Mutterleib schädigen')
Hphrase.create(title:'H360FD', description: 'Kann die Fruchtbarkeit beeinträchtigen Kann das Kind im Mutterleib schädigen')
Hphrase.create(title:'H360Fd', description: 'Kann die Fruchtbarkeit beeinträchtigen Kann vermutlich das Kind im Mutterleib schädigen')
Hphrase.create(title:'H360Df', description: 'Kann das Kind im Mutterleib schädigen Kann vermutlich die Fruchtbarkeit beeinträchtigen')
Hphrase.create(title:'H361', description: 'Kann vermutlich die Fruchtbarkeit beeinträchtigen oder das Kind im Mutterleib schädigen (konkrete Wirkung angeben, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass die Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H361f', description: 'Kann vermutlich die Fruchtbarkeit beeinträchtigen')
Hphrase.create(title:'H361d', description: 'Kann vermutlich das Kind im Mutterleib schädigen')
Hphrase.create(title:'H361fd', description: 'Kann vermutlich die Fruchtbarkeit beeinträchtigen Kann vermutlich das Kind im Mutterleib schädigen')
Hphrase.create(title:'H362', description: 'Kann Säuglinge über die Muttermilch schädigen')
Hphrase.create(title:'H370', description: 'Schädigt die Organe (oder alle betroffenen Organe nennen, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H371', description: 'Kann die Organe schädigen (oder alle betroffenen Organe nennen, sofern bekannt) (Expositionsweg angeben, sofern schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H372', description: 'Schädigt die Organe (alle betroffenen Organe nennen) bei längerer oder wiederholter Exposition (Expositionsweg angeben, wenn schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H373', description: 'Kann die Organe schädigen (alle betroffenen Organe nennen, sofern bekannt) bei längerer oder wiederholter Exposition (Expositionsweg angeben, wenn schlüssig belegt ist, dass diese Gefahr bei keinem anderen Expositionsweg besteht)')
Hphrase.create(title:'H300+H310', description: 'Lebensgefahr bei Verschlucken oder Hautkontakt')
Hphrase.create(title:'H300+H310+H330', description: 'Lebensgefahr bei Verschlucken, Hautkontakt oder Einatmen')
Hphrase.create(title:'H300+H330', description: 'Lebensgefahr bei Verschlucken oder Einatmen')
Hphrase.create(title:'H301+H311', description: 'Giftig bei Verschlucken oder Hautkontakt')
Hphrase.create(title:'H301+H311+H331', description: 'Giftig bei Verschlucken, Hautkontakt oder Einatmen')
Hphrase.create(title:'H301+H331', description: 'Giftig bei Verschlucken oder Einatmen')
Hphrase.create(title:'H302+H312', description: 'Gesundheitsschädlich bei Verschlucken oder Hautkontakt')
Hphrase.create(title:'H302+H312+H332', description: 'Gesundheitsschädlich bei Verschlucken, Hautkontakt oder Einatmen')
Hphrase.create(title:'H302+H332', description: 'Gesundheitsschädlich bei Verschlucken oder Einatmen')
Hphrase.create(title:'H310+H330', description: 'Lebensgefahr bei Hautkontakt oder Einatmen')
Hphrase.create(title:'H311+H331', description: 'Giftig bei Hautkontakt oder Einatmen')
Hphrase.create(title:'H312+H332', description: 'Gesundheitsschädlich bei Hautkontakt oder Einatmen')
Hphrase.create(title:'H400', description: 'Sehr giftig für Wasserorganismen')
Hphrase.create(title:'H410', description: 'Sehr giftig für Wasserorganismen mit langfristiger Wirkung')
Hphrase.create(title:'H411', description: 'Giftig für Wasserorganismen, mit langfristiger Wirkung')
Hphrase.create(title:'H412', description: 'Schädlich für Wasserorganismen, mit langfristiger Wirkung')
Hphrase.create(title:'H413', description: 'Kann für Wasserorganismen schädlich sein, mit langfristiger Wirkung')
Hphrase.create(title:'H420', description: 'Schädigt die öffentliche Gesundheit und die Umwelt durch Ozonabbau in der äußeren Atmosphäre')

Pphrase.create(title:'P101', description: 'Ist ärztlicher Rat erforderlich, Verpackung oder Kennzeichnungsetikett bereithalten')
Pphrase.create(title:'P102', description: 'Darf nicht in die Hände von Kindern gelangen')
Pphrase.create(title:'P103', description: 'Vor Gebrauch Kennzeichnungsetikett lesen')
Pphrase.create(title:'P201', description: 'Vor Gebrauch alle Sicherheitshinweise lesen und verstehen.')
Pphrase.create(title:'P202', description: 'Von Hitze, heißen Oberflächen, Funken, offenen Flammen sowie anderen Zündquellenarten fernhalten. Nicht rauchen.')
Pphrase.create(title:'P210', description: 'Nicht gegen offene Flamme oder andere Zündquelle sprühen.')
Pphrase.create(title:'P211', description: 'Von Kleidung /…/ brennbaren Materialien fernhalten/entfernt aufbewahren.')
Pphrase.create(title:'P220', description: 'Berührung mit Luft vermeiden.')
Pphrase.create(title:'P222', description: 'Keinen Kontakt mit Wasser zulassen.')
Pphrase.create(title:'P223', description: 'Feucht halten mit … .')
Pphrase.create(title:'P230', description: 'Unter inertem Gas handhaben.')
Pphrase.create(title:'P231', description: 'Vor Feuchtigkeit schützen.')
Pphrase.create(title:'P232', description: 'Behälter dicht verschlossen halten.')
Pphrase.create(title:'P233', description: 'Nur im Originalbehälter aufbewahren.')
Pphrase.create(title:'P234', description: 'Kühl halten.')
Pphrase.create(title:'P235', description: 'Behälter und zu befüllende Anlage erden.')
Pphrase.create(title:'P240', description: 'Explosionsgeschützte elektrische Betriebsmittel / Lüftungsanlagen / Beleuchtung / … verwenden.')
Pphrase.create(title:'P241', description: 'Nur funkenfreies Werkzeug verwenden.')
Pphrase.create(title:'P242', description: 'Maßnahmen gegen elektrostatische Entladungen treffen.')
Pphrase.create(title:'P243', description: 'Druckminderer frei von Fett und Öl halten.')
Pphrase.create(title:'P244', description: 'Nicht schleifen / stoßen / … / reiben.')
Pphrase.create(title:'P250', description: 'Nicht durchstechen oder verbrennen, auch nicht nach der Verwendung.')
Pphrase.create(title:'P251', description: 'Staub / Rauch / Gas / Nebel / Dampf / Aerosol nicht einatmen.')
Pphrase.create(title:'P260', description: 'Einatmen von Staub / Rauch / Gas / Nebel / Dampf / Aerosol vermeiden.')
Pphrase.create(title:'P261', description: 'Nicht in die Augen, auf die Haut oder auf die Kleidung gelangen lassen.')
Pphrase.create(title:'P262', description: 'Kontakt während der Schwangerschaft / und der Stillzeit vermeiden.')
Pphrase.create(title:'P263', description: 'Nach Gebrauch … gründlich waschen.')
Pphrase.create(title:'P264', description: 'Bei Gebrauch nicht essen, trinken oder rauchen.')
Pphrase.create(title:'P270', description: 'Nur im Freien oder in gut belüfteten Räumen verwenden.')
Pphrase.create(title:'P271', description: 'Kontaminierte Arbeitskleidung nicht außerhalb des Arbeitsplatzes tragen.')
Pphrase.create(title:'P272', description: 'Freisetzung in die Umwelt vermeiden.')
Pphrase.create(title:'P273', description: 'Schutzhandschuhe / Schutzkleidung / Augenschutz / Gesichtsschutz tragen.')
Pphrase.create(title:'P280', description: 'Schutzhandschuhe / Gesichtsschild / Augenschutz mit Kälteisolierung tragen.')
Pphrase.create(title:'P282', description: 'Schwer entflammbare / flammhemmende Kleidung tragen.')
Pphrase.create(title:'P283', description: 'Atemschutz tragen.')
Pphrase.create(title:'P284', description: 'Unter inertem Gas handhaben. Vor Feuchtigkeit schützen.')
Pphrase.create(title:'P231+P232', description: 'Bei Verschlucken:')
Pphrase.create(title:'P301', description: 'Bei Berührung mit der Haut')
Pphrase.create(title:'P302', description: 'Bei Berührung mit der Haut oder dem Haar')
Pphrase.create(title:'P303', description: 'Bei Einatmen')
Pphrase.create(title:'P304', description: 'Bei Kontakt mit den Augen')
Pphrase.create(title:'P305', description: 'Bei kontaminierter Kleidung')
Pphrase.create(title:'P306', description: 'Bei Exposition oder falls betroffen')
Pphrase.create(title:'P308', description: 'Sofort Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P310', description: 'Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P311', description: 'Bei Unwohlsein Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P312', description: 'Ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P313', description: 'Bei Unwohlsein ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P314', description: 'Sofort ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P315', description: 'Besondere Behandlung dringend erforderlich (siehe … auf diesem Kennzeichnungsetikett).')
Pphrase.create(title:'P320', description: 'Besondere Behandlung (siehe … auf diesem Kennzeichnungsetikett).')
Pphrase.create(title:'P321', description: 'Mund ausspülen.')
Pphrase.create(title:'P330', description: 'Kein Erbrechen herbeiführen.')
Pphrase.create(title:'P331', description: 'Bei Hautreizung:')
Pphrase.create(title:'P332', description: 'Bei Hautreizung oder -ausschlag:')
Pphrase.create(title:'P333', description: 'In kaltes Wasser tauchen / nassen Verband anlegen.')
Pphrase.create(title:'P334', description: 'Lose Partikel von der Haut abbürsten.')
Pphrase.create(title:'P335', description: 'Vereiste Bereiche mit lauwarmem Wasser auftauen. Betroffenen Bereich nicht reiben.')
Pphrase.create(title:'P336', description: 'Bei anhaltender Augenreizung:')
Pphrase.create(title:'P337', description: 'Eventuell vorhandene Kontaktlinsen nach Möglichkeit entfernen. Weiter ausspülen.')
Pphrase.create(title:'P338', description: 'Die betroffene Person an die frische Luft bringen und für ungehinderte Atmung sorgen.')
Pphrase.create(title:'P340', description: 'Bei Symptomen der Atemwege:')
Pphrase.create(title:'P342', description: 'Einige Minuten lang behutsam mit Wasser ausspülen.')
Pphrase.create(title:'P351', description: 'Mit viel Wasser / … waschen.')
Pphrase.create(title:'P352', description: 'Haut mit Wasser abwaschen / duschen.')
Pphrase.create(title:'P353', description: 'Kontaminierte Kleidung und Haut sofort mit viel Wasser abwaschen und danach Kleidung ausziehen.')
Pphrase.create(title:'P360', description: 'Alle kontaminierten Kleidungsstücke sofort ausziehen.')
Pphrase.create(title:'P361', description: 'Kontaminierte Kleidung ausziehen.')
Pphrase.create(title:'P362', description: 'Kontaminierte Kleidung vor erneutem Tragen waschen.')
Pphrase.create(title:'P363', description: 'Und vor erneutem Tragen waschen.')
Pphrase.create(title:'P364', description: 'Bei Brand')
Pphrase.create(title:'P370', description: 'Bei Großbrand und großen Mengen')
Pphrase.create(title:'P371', description: 'Explosionsgefahr bei Brand.')
Pphrase.create(title:'P372', description: 'Keine Brandbekämpfung, wenn das Feuer explosive Stoffe / Gemische / Erzeugnisse erreicht.')
Pphrase.create(title:'P373', description: 'Wegen Explosionsgefahr Brand aus der Entfernung bekämpfen.')
Pphrase.create(title:'P375', description: 'Undichtigkeit beseitigen, wenn gefahrlos möglich.')
Pphrase.create(title:'P376', description: 'Brand von ausströmendem Gas: Nicht löschen, bis Undichtigkeit gefahrlos beseitigt werden kann.')
Pphrase.create(title:'P377', description: '… zum Löschen verwenden.')
Pphrase.create(title:'P378', description: 'Umgebung räumen.')
Pphrase.create(title:'P380', description: 'Alle Zündquellen entfernen, wenn gefahrlos möglich.')
Pphrase.create(title:'P381', description: 'Verschüttete Mengen aufnehmen, um Materialschäden zu vermeiden.')
Pphrase.create(title:'P390', description: 'Verschüttete Mengen aufnehmen.')
Pphrase.create(title:'P391', description: 'Bei Verschlucken: Sofort Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P301+P310', description: 'Bei Verschlucken: Bei Unwohlsein Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P301+P312', description: 'Bei Verschlucken: Mund ausspülen. Kein Erbrechen herbeiführen.')
Pphrase.create(title:'P301+P330+P331', description: 'Bei Kontakt mit der Haut: In kaltes Wasser tauchen / nassen Verband anlegen.')
Pphrase.create(title:'P302+P334', description: 'Bei Berührung mit der Haut: Lose Partikel von der Haut abbürsten. In kaltes Wasser tauchen [oder nassen Verband anlegen].')
Pphrase.create(title:'P302+P335+P334', description: 'Bei Berührung mit der Haut: Mit viel Wasser / … waschen. (Bis zum Inkrafttreten der 4. ATP am 1. Dezember 2014: Bei Kontakt mit der Haut: Mit viel Wasser und Seife waschen.)')
Pphrase.create(title:'P302+P352', description: 'Bei Kontakt mit der Haut (oder dem Haar): Alle beschmutzten, getränkten Kleidungsstücke sofort ausziehen. Haut mit Wasser abwaschen/duschen.')
Pphrase.create(title:'P303+P361+P353', description: 'Bei Einatmen: Die Person an die frische Luft bringen und für ungehinderte Atmung sorgen.')
Pphrase.create(title:'P304+P340', description: 'Bei Kontakt mit den Augen: Einige Minuten lang behutsam mit Wasser spülen. Vorhandene Kontaktlinsen nach Möglichkeit entfernen. Weiter spülen.')
Pphrase.create(title:'P305+P351+P338', description: 'Bei Kontakt mit der Kleidung: Kontaminierte Kleidung und Haut sofort mit viel Wasser abwaschen und danach Kleidung ausziehen.')
Pphrase.create(title:'P306+P360', description: 'Bei Exposition oder falls betroffen: Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P308+P311', description: 'Bei Exposition oder falls betroffen: Ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P308+P313', description: 'Bei Hautreizung: Ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P332+P313', description: 'Bei Hautreizung oder -ausschlag: Ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P333+P313', description: 'Vereiste Bereiche mit lauwarmem Wasser auftauen. Betroffenen Bereich nicht reiben. Sofort ärztlichen Rat einholen/ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P336+P315', description: 'Bei anhaltender Augenreizung: Ärztlichen Rat einholen / ärztliche Hilfe hinzuziehen.')
Pphrase.create(title:'P337+P313', description: 'Bei Symptomen der Atemwege: Giftinformationszentrum, Arzt oder … anrufen.')
Pphrase.create(title:'P342+P311', description: 'Alle kontaminierten Kleidungsstücke sofort ausziehen und vor erneutem Tragen waschen.')
Pphrase.create(title:'P361+P364', description: 'Kontaminierte Kleidung ausziehen und vor erneutem Tragen waschen.')
Pphrase.create(title:'P362+P364', description: 'Bei Brand: Undichtigkeit beseitigen, wenn gefahrlos möglich.')
Pphrase.create(title:'P370+P376', description: 'Bei Brand: … zum Löschen verwenden.')
Pphrase.create(title:'P370+P378', description: 'Bei Brand: Umgebung räumen. Wegen Explosionsgefahr Brand aus der Entfernung bekämpfen.')
Pphrase.create(title:'P370+P380+P375', description: 'Bei Großbrand und großen Mengen: Umgebung räumen. Wegen Explosionsgefahr Brand aus der Entfernung bekämpfen.')
Pphrase.create(title:'P371+P380+P375', description: 'Bei Brand: Explosionsgefahr. Umgebung räumen. KEINE Brandbekämpfung, wenn das Feuer explosive Stoffe/Gemische/Erzeugnisse erreicht.')
Pphrase.create(title:'P370+P372+P380+P373', description: 'Bei Brand: Umgebung räumen. Wegen Explosionsgefahr Brand aus der Entfernung bekämpfen.')
Pphrase.create(title:'P370+P380+P375+[P378]', description: '… aufbewahren.')
Pphrase.create(title:'P401', description: 'An einem trockenen Ort aufbewahren.')
Pphrase.create(title:'P402', description: 'An einem gut belüfteten Ort aufbewahren.')
Pphrase.create(title:'P403', description: 'In einem geschlossenen Behälter aufbewahren.')
Pphrase.create(title:'P404', description: 'Unter Verschluss aufbewahren.')
Pphrase.create(title:'P405', description: 'In korrosionsbeständigem / … Behälter mit korrosionsbeständiger Auskleidung aufbewahren.')
Pphrase.create(title:'P406', description: 'Luftspalt zwischen Stapeln / Paletten lassen.')
Pphrase.create(title:'P407', description: 'Vor Sonnenbestrahlung schützen.')
Pphrase.create(title:'P410', description: 'Bei Temperaturen von nicht mehr als … °C / … aufbewahren.')
Pphrase.create(title:'P411', description: 'Nicht Temperaturen von mehr als 50 °C aussetzen.')
Pphrase.create(title:'P412', description: 'Schüttgut in Mengen von mehr als … kg bei Temperaturen von nicht mehr als … °C aufbewahren.')
Pphrase.create(title:'P413', description: 'Von anderen Materialien entfernt aufbewahren.')
Pphrase.create(title:'P420', description: 'In einem geschlossenen Behälter an einem trockenen Ort aufbewahren.')
Pphrase.create(title:'P402+P404', description: 'Behälter dicht verschlossen an einem gut belüfteten Ort aufbewahren.')
Pphrase.create(title:'P403+P233', description: 'Kühl an einem gut belüfteten Ort aufbewahren.')
Pphrase.create(title:'P403+P235', description: 'Vor Sonnenbestrahlung geschützt an einem gut belüfteten Ort aufbewahren.')
Pphrase.create(title:'P410+P403', description: 'Vor Sonnenbestrahlung schützen und nicht Temperaturen von mehr als 50 °C aussetzen.')
Pphrase.create(title:'P410+P412', description: 'Kühl und bei Temperaturen von nicht mehr als … °C aufbewahren.')
Pphrase.create(title:'P411+P235', description: 'Inhalt / Behälter … zuführen.')
Pphrase.create(title:'P501', description: 'Informationen zur Wiederverwendung/Wiederverwertung beim Hersteller/Lieferanten erfragen.')
Pphrase.create(title:'P502', description: '')

Rphrase.create(title:'R1', description: 'In trockenem Zustand explosionsgefährlich')
Rphrase.create(title:'R2', description: 'Durch Schlag, Reibung, Feuer und andere Zündquellen explosionsgefährlich')
Rphrase.create(title:'R3', description: 'Durch Schlag, Reibung, Feuer und andere Zündquellen besonders explosionsgefährlich')
Rphrase.create(title:'R4', description: 'Bildet hochempfindliche explosionsgefährliche Metallverbindungen')
Rphrase.create(title:'R5', description: 'Beim Erwärmen explosionsfähig')
Rphrase.create(title:'R6', description: 'Mit und ohne Luft explosionsfähig')
Rphrase.create(title:'R7', description: 'Kann Brand verursachen')
Rphrase.create(title:'R8', description: '[[Feuergefahr]] bei Berührung mit brennbaren Stoffen.')
Rphrase.create(title:'R9', description: 'Explosionsgefahr bei Mischung mit brennbaren Stoffen')
Rphrase.create(title:'R10', description: 'Entzündlich')
Rphrase.create(title:'R11', description: 'Leichtentzündlich')
Rphrase.create(title:'R12', description: 'Hochentzündlich')
Rphrase.create(title:'R14', description: 'Reagiert heftig mit Wasser')
Rphrase.create(title:'R15', description: 'Reagiert mit Wasser unter Bildung hochentzündlicher Gase')
Rphrase.create(title:'R16', description: 'Explosionsgefährlich in Mischung mit brandfördernden Stoffen')
Rphrase.create(title:'R17', description: '[[Selbstentzündung|Selbstentzündlich]] an der Luft')
Rphrase.create(title:'R18', description: 'Bei Gebrauch Bildung explosionsfähiger /leicht-entzündlicher Dampf-Luftgemische möglich')
Rphrase.create(title:'R19', description: 'Kann explosionsfähige [[Peroxide]] bilden')
Rphrase.create(title:'R20', description: 'Gesundheitsschädlich beim Einatmen')
Rphrase.create(title:'R21', description: 'Gesundheitsschädlich bei Berührung mit der Haut')
Rphrase.create(title:'R22', description: 'Gesundheitsschädlich beim Verschlucken}')
Rphrase.create(title:'R23', description: 'Giftig beim Einatmen')
Rphrase.create(title:'R24', description: 'Giftig bei Berührung mit der Haut')
Rphrase.create(title:'R25', description: 'Giftig beim Verschlucken')
Rphrase.create(title:'R26', description: 'Sehr giftig beim Einatmen')
Rphrase.create(title:'R27', description: 'Sehr giftig bei Berührung mit der Haut')
Rphrase.create(title:'R28', description: 'Sehr giftig beim Verschlucken')
Rphrase.create(title:'R29', description: 'Entwickelt bei Berührung mit Wasser giftige Gase')
Rphrase.create(title:'R30', description: 'Kann bei Gebrauch leicht entzündlich werden')
Rphrase.create(title:'R31', description: 'Entwickelt bei Berührung mit Säure giftige Gase')
Rphrase.create(title:'R32', description: 'Entwickelt bei Berührung mit Säure sehr giftige Gase')
Rphrase.create(title:'R33', description: 'Gefahr kumulativer Wirkungen')
Rphrase.create(title:'R34', description: 'Verursacht [[Verätzung]]en')
Rphrase.create(title:'R35', description: 'Verursacht schwere Verätzungen')
Rphrase.create(title:'R36', description: 'Reizt die Augen')
Rphrase.create(title:'R37', description: 'Reizt die Atmungsorgane')
Rphrase.create(title:'R38', description: 'Reizt die Haut')
Rphrase.create(title:'R39', description: 'Ernste Gefahr irreversiblen Schadens')
Rphrase.create(title:'R40', description: 'Verdacht auf [[krebserzeugend]]e Wirkung')
Rphrase.create(title:'R41', description: 'Gefahr ernster Augenschäden')
Rphrase.create(title:'R42', description: 'Sensibilisierung durch Einatmen möglich')
Rphrase.create(title:'R43', description: 'Sensibilisierung durch Hautkontakt möglich')
Rphrase.create(title:'R44', description: 'Explosionsgefahr bei Erhitzen unter Einschluss')
Rphrase.create(title:'R45', description: 'Kann Krebs erzeugen')
Rphrase.create(title:'R46', description: 'Kann vererbbare Schäden verursachen')
Rphrase.create(title:'R48', description: 'Gefahr ernster Gesundheitsschäden bei längerer Exposition')
Rphrase.create(title:'R49', description: 'Kann Krebs erzeugen beim Einatmen')
Rphrase.create(title:'R50', description: 'Sehr giftig für Wasserorganismen')
Rphrase.create(title:'R51', description: 'Giftig für Wasserorganismen')
Rphrase.create(title:'R52', description: 'Schädlich für Wasserorganismen')
Rphrase.create(title:'R53', description: 'Kann in [[Gewässer]]n längerfristig schädliche Wirkungen haben')
Rphrase.create(title:'R54', description: 'Giftig für Pflanzen')
Rphrase.create(title:'R55', description: 'Giftig für Tiere')
Rphrase.create(title:'R56', description: 'Giftig für [[Edaphon|Bodenorganismen]]')
Rphrase.create(title:'R57', description: 'Giftig für [[Bienen]]')
Rphrase.create(title:'R58', description: 'Kann längerfristig schädliche Wirkungen auf die Umwelt haben')
Rphrase.create(title:'R59', description: 'Gefährlich für die [[Ozonschicht]]')
Rphrase.create(title:'R60', description: 'Kann die [[Fortpflanzungsfähigkeit]] beeinträchtigen')
Rphrase.create(title:'R61', description: 'Kann das Kind im Mutterleib schädigen')
Rphrase.create(title:'R62', description: 'Kann möglicherweise die Fortpflanzungsfähigkeit beeinträchtigen')
Rphrase.create(title:'R63', description: 'Kann das Kind im Mutterleib möglicherweise schädigen')
Rphrase.create(title:'R64', description: 'Kann Säuglinge über die [[Muttermilch]] schädigen')
Rphrase.create(title:'R65', description: 'Gesundheitsschädlich: Kann beim Verschlucken Lungenschäden verursachen')
Rphrase.create(title:'R66', description: 'Wiederholter Kontakt kann zu spröder oder rissiger Haut führen')
Rphrase.create(title:'R67', description: 'Dämpfe können Schläfrigkeit und Benommenheit verursachen')
Rphrase.create(title:'R68', description: 'Irreversibler Schaden möglich')
=end
